### ISSUE TITLE
需要手动下载的内容？| ProxyError: HTTPSConnectionPool(host='api.github.com', port=443)

### ISSUE THREAD

**Issue by katie312** [opendatalab/DocLayout-YOLO#69]
您好！感谢团队优秀的工作。
因为网路限制无法访问，已把D4LA数据集，doclayout_yolo_docsynth300k_imgsz1600.pt预训练模型下载到本地，微调命令如下：
`python train.py --data ./D4LA --model m-doclayout --epoch 500 --image-size 1600 --batch-size 64 --project public_dataset/D4LA --plot 1 --optimizer SGD --lr0 0.04 --pretrain xx/DocLayout-YOLO-D4LA-Docsynth300K_pretrained/doclayout_yolo_docsynth300k_imgsz1600.pt `

返回报错：
```
Traceback (most recent call last):
  File "/opt/conda/envs/llama/doclayout_yolo/lib/python3.10/site-packages/urllib3/connectionpool.py", line 775, in urlopen
    self._prepare_proxy(conn)
  File "/opt/conda/envs/llama/doclayout_yolo/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1044, in _prepare_proxy
    conn.connect()
  File "/opt/conda/envs/llama/doclayout_yolo/lib/python3.10/site-packages/urllib3/connection.py", line 710, in connect
    self._tunnel()
  File "/opt/conda/envs/llama/doclayout_yolo/lib/python3.10/site-packages/urllib3/connection.py", line 262, in _tunnel
    raise OSError(f"Tunnel connection failed: {code} {message.strip()}")
OSError: Tunnel connection failed: 403 Forbidden

The above exception was the direct cause of the following exception:

urllib3.exceptions.ProxyError: ('Unable to connect to proxy', OSError('Tunnel connection failed: 403 Forbidden'))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/envs/llama/doclayout_yolo/lib/python3.10/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
  File "/opt/conda/envs/llama/doclayout_yolo/lib/python3.10/site-packages/urllib3/connectionpool.py", line 843, in urlopen
    retries = retries.increment(
  File "/opt/conda/envs/llama/doclayout_yolo/lib/python3.10/site-packages/urllib3/util/retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/doclayout_yolo/assets/releases/tags/v8.1.0 (Caused by ProxyError('Unable to connect to proxy', OSError('Tunnel connection failed: 403 Forbidden')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/team/cv/xx/ocr_project/DocLayout-YOLO/train.py", line 47, in <module>
    model = YOLOv10(model)
  File "/data/team/cv/xx/ocr_project/DocLayout-YOLO/doclayout_yolo/models/yolov10/model.py", line 12, in __init__
    super().__init__(model=model, task=task, verbose=verbose)
  File "/data/team/cv/xx/ocr_project/DocLayout-YOLO/doclayout_yolo/engine/model.py", line 144, in __init__
    self._load(model, task=task)
  File "/data/team/cv/xx/ocr_project/DocLayout-YOLO/doclayout_yolo/engine/model.py", line 233, in _load
    self.model, self.ckpt = attempt_load_one_weight(weights)
  File "/data/team/cv/xx/ocr_project/DocLayout-YOLO/doclayout_yolo/nn/tasks.py", line 807, in attempt_load_one_weight
    ckpt, weight = torch_safe_load(weight)  # load ckpt
  File "/data/team/cv/xx/ocr_project/DocLayout-YOLO/doclayout_yolo/nn/tasks.py", line 724, in torch_safe_load
    file = attempt_download_asset(weight)  # search online if missing locally
  File "/data/team/cv/xx/ocr_project/DocLayout-YOLO/doclayout_yolo/utils/downloads.py", line 450, in attempt_download_asset
    tag, assets = get_github_assets(repo, release)
  File "/data/team/cv/xx/ocr_project/DocLayout-YOLO/doclayout_yolo/utils/downloads.py", line 395, in get_github_assets
    r = requests.get(url)  # github api
  File "/opt/conda/envs/llama/doclayout_yolo/lib/python3.10/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/opt/conda/envs/llama/doclayout_yolo/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/opt/conda/envs/llama/doclayout_yolo/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/conda/envs/llama/doclayout_yolo/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/opt/conda/envs/llama/doclayout_yolo/lib/python3.10/site-packages/requests/adapters.py", line 694, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/doclayout_yolo/assets/releases/tags/v8.1.0 (Caused by ProxyError('Unable to connect to proxy', OSError('Tunnel connection failed: 403 Forbidden')))
```

还是会出现如上访问报错，请问还是需要其他依赖文件模型下载吗？

**Comment by JulioZhao97** [comment]
@katie312 您好，这个是因为ultralytics的逻辑里面需要下载一个```yolov8n.pt```以用于AMP检查，您可以在这里下载：https://github.com/ultralytics/assets/releases/download/v8.2.0/yolov8n.pt，然后放在项目根路径

**Comment by katie312** [comment]
> @katie312 您好，这个是因为ultralytics的逻辑里面需要下载一个`yolov8n.pt`以用于AMP检查，您可以在[这里](https://github.com/ultralytics/assets/releases/download/v8.2.0/yolov8n.pt)下载，然后放在项目根路径

感谢回复！已下载放到项目根目录中（./DocLayout-YOLO/）,但是还是出现原来的报错，同时尝试放到模型路径下，依旧报错。请问具体是放到哪里呢？感谢！

**Comment by JulioZhao97** [comment]
@katie312 麻烦在
```bash
  File "/data/team/cv/xx/ocr_project/DocLayout-YOLO/doclayout_yolo/nn/tasks.py", line 724, in torch_safe_load
    file = attempt_download_asset(weight)  # search online if missing locally
```
这里print一下weight看看是什么呢？

**Comment by katie312** [comment]
> @katie312 麻烦在
> 
> ```shell
>   File "/data/team/cv/xx/ocr_project/DocLayout-YOLO/doclayout_yolo/nn/tasks.py", line 724, in torch_safe_load
>     file = attempt_download_asset(weight)  # search online if missing locally
> ```
> 
> 这里print一下weight看看是什么呢？

感谢回复！
```
# 修改后
def torch_safe_load(weight):
    """
    This function attempts to load a PyTorch model with the torch.load() function. If a ModuleNotFoundError is raised,
    it catches the error, logs a warning message, and attempts to install the missing module via the
    check_requirements() function. After installation, the function again attempts to load the model using torch.load().

    Args:
        weight (str): The file path of the PyTorch model.

    Returns:
        (dict): The loaded PyTorch model.
    """
    print('weight: \n')
    print(weight)
    from doclayout_yolo.utils.downloads import attempt_download_asset
    check_suffix(file=weight, suffix=".pt")
    file = attempt_download_asset(weight)  # search online if missing locally
    try:
        with temporary_modules(
            {
                "doclayout_yolo.yolo.utils": "doclayout_yolo.utils",
                "doclayout_yolo.yolo.v8": "doclayout_yolo.models.yolo",
                "doclayout_yolo.yolo.data": "doclayout_yolo.data",
            }
        ):  # for legacy 8.0 Classify and Pose models
            ckpt = torch.load(file, map_location="cpu")
```
结果输出：

```
weight: 

/data/team/cv/xxx/ocr_project/DocLayout-YOLO/DocLayout-YOLO-D4LA-Docsynth300K_pretrained/doclayout_yolo_docsynth300k_imgsz1600.pt
Traceback (most recent call last):
  File "/opt/conda/envs/llama/doclayout_yolo/lib/python3.10/site-packages/urllib3/connectionpool.py", line 775, in urlopen
    self._prepare_proxy(conn)
  File "/opt/conda/envs/llama/doclayout_yolo/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1044, in _prepare_proxy
    conn.connect()
  File "/opt/conda/envs/llama/doclayout_yolo/lib/python3.10/site-packages/urllib3/connection.py", line 710, in connect
    self._tunnel()
  File "/opt/conda/envs/llama/doclayout_yolo/lib/python3.10/site-packages/urllib3/connection.py", line 262, in _tunnel
    raise OSError(f"Tunnel connection failed: {code} {message.strip()}")
OSError: Tunnel connection failed: 403 Forbidden

The above exception was the direct cause of the following exception:
……

```

看起来weight路径应该没有问题？

**Comment by JulioZhao97** [comment]
@katie312 目前看起来问题是
https://github.com/opendatalab/DocLayout-YOLO/blob/afeb639f981e47ae1961fb0c1ba293250b49b954/doclayout_yolo/utils/downloads.py#L430-L431
这里的代码不知为何虽然传入了本地的model，但是```file.exists()```是```False```，请麻烦您在这里看一下file路径是什么，看看用torch.load相同路径是否可以成功？应该是windows下面导致的路径问题

**Comment by katie312** [comment]
我是在linux底下，排查了一下，原来是路径错误问题😂，模型和下载的名字不一样，现在能正常运行了，麻烦您了
