### ISSUE TITLE
mesh-candidate_bestfit中candidate_num的设置

### ISSUE THREAD

**Issue by katie312** [opendatalab/DocLayout-YOLO#73]
candidate_num默认是500，请问自定义element_pool的话要根据什么参数去修改呢？修改成多少比较合适呢？

**Comment by JulioZhao97** [comment]
@katie312 您好！这里的逻辑是对于每一个layout，先生称一个大小为candidate_num的候选池子，然后元素从这个候选池子里选择；这个值的设置是相对独立的，例如以M6Doc内的元素为例，绝大多数生成的layout都不会包含超过25个元素，所以选择500个作为候选池子足够保证随机性

**Comment by katie312** [comment]
> @katie312 您好！这里的逻辑是对于每一个layout，先生称一个大小为candidate_num的候选池子，然后元素从这个候选池子里选择；这个值的设置是相对独立的，例如以M6Doc内的元素为例，绝大多数生成的layout都不会包含超过25个元素，所以选择500个作为候选池子足够保证随机性

感谢回复
我目前先用了少量的元素去做生成,但是用默认candidate_num=500会报错,
```
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/opt/conda/envs/llama/doclayout_yolo/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/opt/conda/envs/llama/doclayout_yolo/lib/python3.10/multiprocessing/pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/data/team/cv/liusj/ocr_project/DocLayout-YOLO/mesh-candidate_bestfit/bestfit_generator.py", line 26, in bestfit_generator
    large_elements_idx = random.sample(list(range(len(element_all['large']))), int(candidate_num*0.99))
  File "/opt/conda/envs/llama/doclayout_yolo/lib/python3.10/random.py", line 482, in sample
    raise ValueError("Sample larger than population or is negative")
ValueError: Sample larger than population or is negative
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/team/cv/liusj/ocr_project/DocLayout-YOLO/mesh-candidate_bestfit/bestfit_generator.py", line 139, in <module>
    generated_layout = p.starmap(
  File "/opt/conda/envs/llama/doclayout_yolo/lib/python3.10/multiprocessing/pool.py", line 375, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/opt/conda/envs/llama/doclayout_yolo/lib/python3.10/multiprocessing/pool.py", line 774, in get
    raise self._value
ValueError: Sample larger than population or is negative
```

我把代码修增加了对列表大小的检查，确保不会从列表中抽取比列表长度更多的样本,就可以了

```
large_sample_count = min(int(candidate_num * 0.99), large_count)
small_sample_count = min(int(candidate_num * 0.01), small_count)

large_elements_idx = random.sample(list(range(large_count)), large_sample_count) if large_count > 0 else []
small_elements_idx = random.sample(list(range(small_count)), small_sample_count) if small_count > 0 else []
```

但是我怕对生成效果有影响,又尝试基于源代码去调整candidate_num的值,但是需要调到比较小的数值(eg: 2),也可以运行成功|

另外想问一下,目前candidate_num的算法逻辑应该没有针对元素之间的关系去做匹配度的判断?只是从填充率去做判断?
比如image 以及 image_header, 合理的布局应该需要匹配到一起.

**Comment by JulioZhao97** [comment]
@katie312 现在暂时只考虑填充度，类别的合理性在后续的版本中会更新，如果您需要考虑类合理性的layout生成，您可以参考基于diffusion的生成方法，例如[LACE](https://github.com/puar-playground/LACE)

**Comment by katie312** [comment]
好的，感谢，我去了解一下
